[package]
name = "jinjiang"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    ".",
    "prisma-cli",
    "server",
    "cli",
]

[dependencies]
server = { path = "server" }
tokio = { version = "1.31.0", features = ["full"]}
anyhow = "1.0.72"
