name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/head/master' }}

      - name: Build project
        run: |
          cargo run -p prisma-cli -- generate
          cargo build --release -p jinjiang-cli
          ls target/release/jinjiang*
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: cangzhang/jinjiang:latest
          # platforms: linux/amd64,linux/arm64