name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/head/master' }}

      - name: Build project
        run: |
          cargo run -p prisma-cli -- generate
          cargo build --release -p jinjiang-cli -p jinjiang
          docker build . -t cangzhang/jinjiang:$GITHUB_SHA
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push cangzhang/jinjiang:$GITHUB_SHA
